<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select State</name>
   <tag></tag>
   <elementGuidId>6db1f96b-fe6a-46ce-9b30-4c807a798389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#state > div.css-13cymwt-control > div.css-hlgwow > div.css-19bb58m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='state']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d303005c-0082-4d75-a579-d74b6f1f4302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19bb58m</value>
      <webElementGuid>828d7b7b-64d7-4726-8652-00e4077c977c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state&quot;)/div[@class=&quot;css-13cymwt-control&quot;]/div[@class=&quot;css-hlgwow&quot;]/div[@class=&quot;css-19bb58m&quot;]</value>
      <webElementGuid>ec22c864-84aa-4f6e-b477-1aaca4a46766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='state']/div/div/div[2]</value>
      <webElementGuid>c7906408-01fa-4ffa-b4d8-6fee57572ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select State'])[1]/following::div[1]</value>
      <webElementGuid>adb7815d-8aee-41c8-a3f7-d3d703332b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State and City'])[1]/following::div[6]</value>
      <webElementGuid>4cc91a26-3be9-4e69-ba2f-11153ec6c3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select City'])[1]/preceding::div[3]</value>
      <webElementGuid>7bd4eb84-8e3d-47c1-bc72-3f1a08b16176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[11]</value>
      <webElementGuid>5e1e325e-a31f-4ec7-92fe-073d041f9a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>29d1bd7e-13b0-4967-bc0a-8f06b484dc47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
