<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reading</name>
   <tag></tag>
   <elementGuidId>eb1d6648-8124-40aa-a15d-725774e378e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.form-check:nth-child(2) [type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 2)]//*[@type = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d89f8d49-530d-4782-996a-8abeb8c0ad65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies-checkbox-2</value>
      <webElementGuid>66e6b168-3e78-40da-9b76-477f88d229b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>10c541aa-41b9-4276-aa4e-95f8977f7a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e43e2dec-0d0e-4b88-86c5-8d9383fa2804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>884a37db-6c11-4a9f-bda3-7cbbdf67c3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-440022e1a46364ec96df7763af6cd24e</value>
      <webElementGuid>cbc50d2e-cbcf-4fb5-8206-5d5c9c073a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 2)]//*[@type = 'checkbox']</value>
      <webElementGuid>d21f2d0f-279c-4f18-9b53-76a7d436c31f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 2)]//*[@type = 'checkbox']</value>
      <webElementGuid>79f4ed0c-ac98-4eb8-85b9-aa9405deb87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hobbies-checkbox-2' and @type = 'checkbox']</value>
      <webElementGuid>e4d44416-b235-4497-9ab9-b1de58d8448e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
