<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hobbies_Sports</name>
   <tag></tag>
   <elementGuidId>1e0345f1-4e5d-4018-be96-bcda8defddb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbies-checkbox-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hobbies-checkbox-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b41ba99-7ed0-49d1-b392-5d092eeeda29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies-checkbox-1</value>
      <webElementGuid>60cb8408-b2c3-49ec-9a05-767ca00a1bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d3cbbfc2-724f-4fa8-ba1e-a973e33ff416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7e14c213-1f86-458a-80af-04c4019632df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>309d8668-3358-420c-b587-e636ff375131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies-checkbox-1&quot;)</value>
      <webElementGuid>e24a9232-e613-4217-9a20-d8917f44cb06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies-checkbox-1']</value>
      <webElementGuid>5f6054fd-d986-4590-aa8d-1ab22e6e38c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hobbiesWrapper']/div[2]/div/input</value>
      <webElementGuid>d5065099-4d2d-48c4-ae35-af67df579286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>1332af9d-74af-4d8f-b524-f1a380cdf1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hobbies-checkbox-1' and @type = 'checkbox']</value>
      <webElementGuid>a0c8b7e5-b0e6-48e1-9835-eecbea2f7857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
