<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-city</name>
   <tag></tag>
   <elementGuidId>67f8f75c-da77-4596-8eff-939bc2731f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city [data-value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'city']//*[@data-value = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53681e26-efd6-4258-8233-eebdd12f0bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19bb58m</value>
      <webElementGuid>563cca37-200c-4984-8d75-a8f08cb4e615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4b59e5c1549f53083cfeb1bfa2e52276</value>
      <webElementGuid>562513fe-0fc9-4c9a-9e59-c83b942d954e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'city']//*[@data-value = '']</value>
      <webElementGuid>55099478-00e7-455c-a37b-cc0c8908f0f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'city']//*[@data-value = '']</value>
      <webElementGuid>68fd0222-ce60-4517-9b0c-ef011495bd2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
