<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-state</name>
   <tag></tag>
   <elementGuidId>332463ab-e11a-4814-9bbc-8014e43f4e8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#state [data-value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'state']//*[@data-value = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e042295-1e31-4160-bc20-c5a3b0d0f156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19bb58m</value>
      <webElementGuid>f2031320-e3a7-4447-9587-ecc1b0bf8cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0cb8eac2dd90cb9612ca209195bc8a10</value>
      <webElementGuid>5a188823-20fd-4915-938f-08b7b367a161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'state']//*[@data-value = '']</value>
      <webElementGuid>e201e3af-d92e-4e4a-b34d-e2e0f0437c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'state']//*[@data-value = '']</value>
      <webElementGuid>fbfb6aa9-ac9f-447e-9b0d-f92b2b0c6141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
