<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>state_NCR</name>
   <tag></tag>
   <elementGuidId>df0af8cc-9a69-4ad7-878a-cdcc73b2602f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@role = 'option') and (position() = 1)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e81cb45-75dc-4856-88ab-d9578a1da353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-10wo9uf-option</value>
      <webElementGuid>4a912342-b5f1-4775-8cee-41c31676b762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6ef696e-43a9-4e11-8781-3da84cf87a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-3-option-0</value>
      <webElementGuid>f4f44a44-00dc-4333-bfd5-ba0d4f58764d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5394f97a-3655-4443-9b14-e80fab4d6b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2d30b1b0-d946-4e4e-8b5f-585ce0cad12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cdf9ed6b-ba1a-4c42-ad1a-5a942869295f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NCR</value>
      <webElementGuid>6c1b6085-fb2a-41ac-a3b9-f0a41485e21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b5a7388a68fb2b08bb910a353a5f5f6b</value>
      <webElementGuid>479bf0f7-88ba-4493-add0-947fc986ace4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 1)]</value>
      <webElementGuid>8ac9dbb6-fa98-4d0b-b713-2be644da8483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@role = 'option') and (position() = 1)]</value>
      <webElementGuid>f46bf874-f432-4b21-8b66-0164af3f4adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-3-option-0' and (text() = 'NCR' or . = 'NCR')]</value>
      <webElementGuid>a00d0902-9735-4582-b4b6-cd125117834c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
